[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Debian"]





[window]
startup_mode = "Maximized"
padding = { x = 8, y = 8 }
opacity = 0.97
blur = true

[scrolling]
history = 5000
multiplier = 3






[font]
size = 10

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Mono Bold"
style = "Regular"

[font.italic]
family = "0xProto Nerd Font Mono Italic"
style = "Regular"






[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#11121D'  
foreground = '#a9b1d6'

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"



[cursor]
style = "Beam"


[colors.cursor]
text = "#1e1e2e"   
cursor = "#f5c2e7" 




[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"




[[keyboard.bindings]]

    action = "SpawnNewInstance"
    key    = "N"
    mods   = "Control"


 
